name = "Starlark"
grammar = "starlark"
path_suffixes = ["star"]
line_comments = ["# "]

[brackets]
enabled = true

[[brackets.pairs]]
start = "{"
end = "}"
close = true
newline = true

[[brackets.pairs]]
start = "["
end = "]"
close = true
newline = true

[[brackets.pairs]]
start = "("
end = ")"
close = true
newline = false

[[brackets.pairs]]
start = "\""
end = "\""
close = true
newline = false
not_in = ["string"]

[[brackets.pairs]]
start = "'"
end = "'"
close = true
newline = false
not_in = ["string"]

[language_servers]
default = "clash-lsp"
